### ISSUE TITLE
Makes Blender 2.93.3 crash on ubuntu 21.10

### ISSUE THREAD

**Issue by j2l** [ubisoft/videotracks#8]
I wanted to install the whole Ubisoft pack (shot manager, stampInfo and videotracks).
When I install the later, it installs with no error, appears in the timeline but as soon as I try to restart blender, it crashes.
If I remove the videotrack folder from my scripts/addons, blender works again.

**Comment by werwack** [comment]
Hi Philippe,
Well, VideoTracks is currently... on a poor track :D
I'm surprised it doesn't work on 2.93 though. 3.1 I would have understood since I still have to clean it up for Python 3.10.

My advice here is forget about this add-on for the moment. It doesn't provide significant features and I'll rework it considerably during summer to make it compliant with the changes of Blender 3.3 regarding VSE and storyboarding.

**Comment by j2l** [comment]
OK, thank you!
Actually, Shot Manager breaks without it but not all the time. Very weird.

**Comment by werwack** [comment]
Arf, that I'm interested in. Hum, can you please use the version 2.0.x that is in Pre Release instead of the 1.7? It is still in beta but that's the one actively supported and there are a lot of fixes and improvements there. I will release another pre release one during the week btw, keep following this page: https://ubisoft-shotmanager.readthedocs.io/en/latest/experimental/experimental.html#experimental

Please post the Shot Manager issues in the SM github. Also note that I've never tested it on other plateforms that win

**Comment by j2l** [comment]
I wrote another ticket about shot manager: https://github.com/ubisoft/shotmanager/issues/26, we could close this one.
